# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-10 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='副标题')),
                ('pages', models.IntegerField(blank=True, verbose_name='页数')),
                ('author', models.CharField(max_length=60, verbose_name='作者')),
                ('translator', models.CharField(blank=True, max_length=60, verbose_name='译者')),
                ('price', models.CharField(blank=True, max_length=60, verbose_name='定价')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='出版社')),
                ('pubdate', models.CharField(blank=True, max_length=60, verbose_name='出版日期')),
                ('cover_img', models.URLField(blank=True, verbose_name='封面图')),
                ('summary', models.TextField(blank=True, max_length=2000, verbose_name='内容简介')),
                ('author_intro', models.TextField(blank=True, max_length=2000, verbose_name='作者简介')),
                ('create_time', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '图书',
                'verbose_name': '图书',
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('email', models.CharField(blank=True, max_length=128)),
                ('contact', models.IntegerField(blank=True, max_length=16)),
                ('status', models.IntegerField(blank=True, verbose_name='借书状态')),
                ('Borrowbooks_time', models.DateField(auto_now=True)),
                ('Backbook_time', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.Book')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='reader',
            unique_together=set([('book', 'account')]),
        ),
    ]
